"use client";

import { useQuery } from "@tanstack/react-query";
import { Bot, Boxes, Siren } from "lucide-react";
import { api } from "@/lib/api";
import { ConsolePanel, PartialState, TruthBadge } from "@/components/console-ui";
import { ErrorState, PageHeader, StateBadge } from "@/components/dashboard-ui";
import { Skeleton } from "@/components/ui/skeleton";

export default function GovernancePage() {
  const tower = useQuery({ queryKey: ["control-tower"], queryFn: api.controlTower });
  const diagnostics = useQuery({ queryKey: ["llm-diagnostics"], queryFn: api.llmDiagnostics });
  if (tower.isLoading) return <Skeleton className="h-[620px] rounded-2xl" />;
  if (tower.error) return <ErrorState error={tower.error} retry={() => void tower.refetch()} />;
  const data = tower.data!;
  return <div><PageHeader eyebrow="Governance" title="Authority remains deterministic" description="Inspect policy disposition, blast-radius limits, kill switches, canary posture, model lifecycle and zero-tool replay evidence." onRefresh={() => { void tower.refetch(); void diagnostics.refetch(); }} refreshing={tower.isFetching || diagnostics.isFetching} updated={new Date(data.generatedAt)} />
    <div className="mb-5 flex flex-wrap gap-2"><TruthBadge label="POLICY DECIDES" /><TruthBadge label="SHADOW ONLY" /><TruthBadge label="PROVIDER CONFIRMED" /></div>
    <section className="grid gap-4 xl:grid-cols-2"><ConsolePanel eyebrow="Recovery Safety Governor" title="Blast-radius envelope"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Limit label="Total value" value={String(data.governor.maxTotalValueMinor)} /><Limit label="Per incident" value={String(data.governor.maxValuePerIncidentMinor)} /><Limit label="Incidents" value={String(data.governor.maxIncidents)} /><Limit label="Provider calls/min" value={String(data.governor.maxProviderCallsPerMinute)} /><Limit label="Concurrent jobs" value={String(data.governor.maxConcurrentJobs)} /><Limit label="Canary size" value={String(data.governor.canarySize)} /></div><p className="mt-5 text-xs leading-5 text-slate-500">Canary expansion requires {data.governor.requiredReconciledCount} provider-confirmed reconciliations. Unreconciled acceptance cannot expand exposure.</p></ConsolePanel>
      <ConsolePanel eyebrow="Mandatory stops" title="Independent kill-switch posture"><div className="space-y-2">{Object.entries(data.governor.killSwitches).map(([name, enabled]) => <div key={name} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white/70 px-3 py-2"><span className="font-mono text-[10px] text-slate-600">{name.replaceAll("_", " ")}</span><StateBadge value={enabled ? "STOPPED" : "APPROVED"} /></div>)}</div></ConsolePanel></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-3"><ConsolePanel eyebrow="Model registry" title="Lifecycle, not authority"><Boxes className="size-4 text-primary" /><div className="mt-4 space-y-3">{data.models.map((model) => <div key={model.id} className="border-b border-slate-200 pb-3 last:border-0"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">{model.name}</p><p className="mt-1 font-mono text-[9px] text-slate-400">{model.version} · {model.featureSchemaVersion}</p></div><StateBadge value={model.lifecycle} /></div></div>)}{data.models.length === 0 && <PartialState title="Deterministic baseline" detail="No registered model is active. This does not weaken policy authority." />}</div></ConsolePanel>
      <ConsolePanel eyebrow="Gemini diagnostic" title="AI state without secrets"><Bot className="size-4 text-primary" />{diagnostics.data ? <div className="mt-4 space-y-3"><Limit label="Provider" value={diagnostics.data.provider} /><Limit label="Configured" value={diagnostics.data.configured ? "Yes" : "No"} /><Limit label="Model" value={diagnostics.data.model} /><Limit label="Last result" value={diagnostics.data.lastResult} /><TruthBadge label={diagnostics.data.lastResult.includes("SUCCESS") ? "OBSERVATIONAL" : "DETERMINISTIC FALLBACK"} /></div> : <PartialState title="Diagnostic unavailable" detail="LLM state cannot be established. Financial authority remains deterministic." />}</ConsolePanel>
      <ConsolePanel eyebrow="Replay and shadow" title="No provider or customer tools"><Siren className="size-4 text-primary" /><div className="mt-4 grid grid-cols-3 gap-2"><Limit label="Snapshots" value={String(data.replayAndShadow.snapshotCount)} /><Limit label="Comparisons" value={String(data.replayAndShadow.comparisonCount)} /><Limit label="Critical" value={String(data.replayAndShadow.criticalRegressionCount)} /></div><div className="mt-4 space-y-3">{data.replayAndShadow.latestDifferences.slice(0, 4).map((difference) => <div key={difference.id} className="rounded-lg border border-slate-200 p-3"><p className="font-mono text-[10px]">{difference.productionAction} → {difference.shadowAction}</p><p className="mt-2 text-xs text-slate-500">{difference.explanation}</p><TruthBadge label="SHADOW ONLY" /></div>)}{data.replayAndShadow.latestDifferences.length === 0 && <p className="text-xs text-slate-500">No material differences are recorded.</p>}</div></ConsolePanel></section>
  </div>;
}
function Limit({ label, value }: { label: string; value: string }) { return <div><p className="font-mono text-sm font-semibold text-slate-800">{value}</p><p className="mt-1 font-mono text-[8px] tracking-[.12em] text-slate-400 uppercase">{label}</p></div>; }
