package com.sentinel.revenue.health;

public enum PaymentHealthSignalType {
    PAYMENT_METHOD_DEGRADATION,
    FAILURE_RATE_SPIKE,
    FAILURE_VELOCITY_SPIKE,
    BANK_CONCENTRATION,
    ERROR_REASON_CONCENTRATION,
    REVENUE_EXPOSURE_SPIKE,
    PROVIDER_DOWNTIME_SIGNAL,
    RECOVERY_TOOL_ERROR_SPIKE
}
