"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { BrainCircuit, Clock3, Coins } from "lucide-react";
import { api, money, shortId } from "@/lib/api";
import { ConsolePanel, PartialState, TruthBadge } from "@/components/console-ui";
import { ErrorState, PageHeader } from "@/components/dashboard-ui";
import { Skeleton } from "@/components/ui/skeleton";

export default function IntelligencePage() {
  const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents });
  const marketplace = useQuery({ queryKey: ["action-marketplace"], queryFn: api.actionMarketplace });
  const [selected, setSelected] = useState("");
  const incidentId = selected || incidents.data?.[0]?.incidentId || "";
  const counterfactuals = useQuery({ queryKey: ["counterfactuals", incidentId], queryFn: () => api.counterfactuals(incidentId), enabled: Boolean(incidentId) });
  const timing = useQuery({ queryKey: ["timing", incidentId], queryFn: () => api.timingRecommendation(incidentId), enabled: Boolean(incidentId) });
  const costs = useQuery({ queryKey: ["recovery-costs", incidentId], queryFn: () => api.recoveryCosts(incidentId), enabled: Boolean(incidentId) });
  const profile = useQuery({ queryKey: ["customer-profile", incidentId], queryFn: () => api.customerRecoveryProfile(incidentId), enabled: Boolean(incidentId) });
  const sorted = useMemo(() => [...(counterfactuals.data ?? [])].sort((a, b) => (b.estimatedNetIncrementalValueMinor ?? -Infinity) - (a.estimatedNetIncrementalValueMinor ?? -Infinity)), [counterfactuals.data]);
  if (incidents.isLoading || marketplace.isLoading) return <Skeleton className="h-[620px] rounded-2xl" />;
  if (incidents.error || marketplace.error) return <ErrorState error={(incidents.error ?? marketplace.error) as Error} retry={() => { void incidents.refetch(); void marketplace.refetch(); }} />;
  return <div><PageHeader eyebrow="Intelligence" title="Recovery economics, before authority" description="Compare first-class NO_ACTION, provider capabilities, counterfactual estimates, timing and observed customer context. Estimates never grant execution permission." />
    <div className="mb-5 flex flex-wrap gap-2"><TruthBadge label="OBSERVATIONAL" /><TruthBadge label="SHADOW ONLY" /><TruthBadge label="NO ACTION IS FIRST-CLASS" /></div>
    <label className="mb-4 block max-w-xl"><span className="eyebrow">Incident context</span><select className="mt-2 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm" value={incidentId} onChange={(event) => setSelected(event.target.value)}>{(incidents.data ?? []).map((item) => <option key={item.incidentId} value={item.incidentId}>{shortId(item.incidentId)} · {item.type.replaceAll("_", " ")}</option>)}</select></label>
    <section className="grid gap-4 xl:grid-cols-2"><ConsolePanel eyebrow="Recovery Action Marketplace" title={`${marketplace.data?.actions.length ?? 0} versioned action capabilities`}><div className="space-y-3">{marketplace.data?.actions.map((action) => <div key={action.action} className="rounded-xl border border-slate-200 bg-white/70 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><p className="font-mono text-xs font-semibold text-slate-800">{action.action.replaceAll("_", " ")}</p><TruthBadge label={action.materiallyExecutable ? action.providerCapability : "NO ACTION"} /></div><p className="mt-2 text-xs text-slate-500">{action.verificationMethod} · risk {action.riskClass.toLowerCase()} · min confidence {(action.minimumConfidence * 100).toFixed(0)}%</p></div>)}{marketplace.data?.actions.length === 0 && <PartialState title="Marketplace unavailable in fixture mode" detail="No action capability metadata is invented without the live backend." />}</div></ConsolePanel>
      <ConsolePanel eyebrow="Counterfactual Recovery Engine" title="Ranked estimates, not recovered money"><div className="space-y-3">{sorted.map((item, index) => <div key={item.action} className="rounded-xl border border-slate-200 bg-white/70 p-4"><div className="flex items-start justify-between gap-3"><div><span className="font-mono text-[9px] text-slate-400">#{index + 1}</span><p className="mt-1 text-sm font-semibold">{item.action.replaceAll("_", " ")}</p></div><TruthBadge label={item.evidenceQuality} /></div><div className="mt-4 grid grid-cols-2 gap-3"><Fact label="Estimated net incremental" value={item.estimatedNetIncrementalValueMinor == null ? "Unknown" : money(item.estimatedNetIncrementalValueMinor)} /><Fact label="Maturity" value={item.maturity} /></div><p className="mt-3 text-xs text-slate-500">{item.method} · model {item.modelVersion}</p></div>)}{!incidentId && <PartialState title="No incident context" detail="Create or select an incident before comparing actions." />}{incidentId && sorted.length === 0 && !counterfactuals.isLoading && <PartialState title="No counterfactual evidence" detail="The current backend did not return estimates; no values were inferred." />}</div></ConsolePanel></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-3"><ConsolePanel eyebrow="Timing and channel" title="When and where"><Clock3 className="size-4 text-primary" />{timing.data ? <><Fact label="Action" value={timing.data.action.replaceAll("_", " ")} /><Fact label="Channel" value={timing.data.channel} /><Fact label="Authority" value={timing.data.authorityState} /><TruthBadge label={timing.data.evidenceQuality} /></> : <PartialState title="Not available" detail="No timing recommendation is available for this incident." />}</ConsolePanel>
      <ConsolePanel eyebrow="Customer context" title="Minimised operational features"><BrainCircuit className="size-4 text-primary" />{profile.data ? <><Fact label="Payment samples" value={String(profile.data.paymentSamples)} /><Fact label="Preferred rail" value={profile.data.preferredPaymentRail} /><Fact label="Promise reliability" value={`${(profile.data.promiseReliability * 100).toFixed(1)}%`} /><TruthBadge label={profile.data.evidenceQuality} /></> : <PartialState title="Not available" detail="No customer profile is exposed; no PII is requested or displayed." />}</ConsolePanel>
      <ConsolePanel eyebrow="Recovery Cost Ledger" title="Cost before value"><Coins className="size-4 text-primary" />{(costs.data ?? []).length ? costs.data?.map((cost) => <div key={cost.id} className="border-b border-slate-200 py-3 last:border-0"><Fact label={cost.costCategory} value={money(cost.amountMinor)} /><TruthBadge label={cost.evidenceQuality} /></div>) : <PartialState title="No cost entries" detail="The ledger has no persisted cost for this incident. Net value remains bounded by available evidence." />}</ConsolePanel></section>
  </div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="mt-3 flex items-start justify-between gap-4 text-xs"><span className="font-mono text-[9px] tracking-wider text-slate-400 uppercase">{label}</span><span className="text-right text-slate-700">{value}</span></div>; }
