package com.sentinel.revenue.opportunity;
public enum OpportunityAction { NO_ACTION, WAIT_FOR_DOWNTIME_RECOVERY, CREATE_PAYMENT_LINK, CREATE_NEW_ORDER, REQUEST_ALTERNATE_METHOD, CUSTOMER_OUTREACH, HUMAN_ESCALATION }
