"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, DatabaseZap, FlaskConical, RotateCcw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api, shortId } from "@/lib/api";
import { mutationErrorMessage } from "@/lib/api-errors";
import { failureLabTrace } from "@/lib/failure-lab";
import { useStatusIsland } from "@/components/providers";
import { PageHeader } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

export default function DemoPage() {
  const client = useQueryClient(); const router = useRouter(); const { emit } = useStatusIsland();
  const [resetOpen, setResetOpen] = useState(false); const [selectedScenario, setSelectedScenario] = useState("upi-outage");
  const scenarios = useQuery({ queryKey: ["failure-lab-scenarios"], queryFn: api.failureLabScenarios });
  const refreshAll = async () => {
    const keys = ["incidents", "metrics", "approvals", "control-tower", "financial-attribution", "lost-revenue"];
    await Promise.all(keys.map((key) => client.invalidateQueries({ queryKey: [key] })));
    await Promise.all(keys.map((key) => client.refetchQueries({ queryKey: [key], type: "active" })));
  };
  const reset = useMutation({ mutationFn: api.reset, onSuccess: async (result) => { await refreshAll(); setResetOpen(false); emit({ title: "Demo reset complete", detail: `${result.incidentsReset} incidents and ${result.eventsReset} payment events reset; audit history preserved` }); toast.success("Synthetic demo state reset. Preserved audit history remains intact."); }, onError: (error: unknown) => toast.error(mutationErrorMessage(error, "reset")) });
  const inject = useMutation({ mutationFn: (scenario: string) => api.injectScenario(scenario), onSuccess: async (result) => { await refreshAll(); const id = result.incidentIds?.[0]; const label = selectedScenario.replaceAll("-", " "); emit({ title: "Scenario injected", detail: id ? `${label} · ${shortId(id)}` : `${label} produced no anomaly` }); toast.success(id ? `${label} passed through ingestion and detection` : `${label} produced no anomaly under current detection rules`); if (id) router.push(`/incidents/${id}`); }, onError: (error: unknown) => toast.error(mutationErrorMessage(error)) });
  const runLab = useMutation({ mutationFn: api.runFailureLab, onSuccess: (result) => { emit({ title: result.safetyDemonstrationPassed ? "Safety behavior evidenced" : "Live evidence required", detail: result.scenario.title }); if (result.safetyDemonstrationPassed) toast.success(result.observedBehavior); else toast.info(result.observedBehavior); }, onError: (error: unknown) => toast.error(mutationErrorMessage(error)) });
  return <div><PageHeader eyebrow="Controlled demonstration" title="Run the Sentinel story" description="Reset synthetic state, inject a labelled UPI outage through the real ingestion and detection pipeline, then operate the incident without Postman." />
    <div className="mb-4 flex flex-wrap gap-2"><span className="test-label">Razorpay Test Mode</span><span className="test-label">Fault injection</span><span className="test-label">Synthetic benchmark</span><span className="test-label">Shadow only</span></div>
    <section className="mb-6 glass-panel rounded-2xl p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">Real ingestion path</p><h2 className="mt-2 text-lg font-semibold">Inject a labelled payment failure</h2><p className="mt-2 text-sm text-muted-foreground">Each scenario uses a distinct Razorpay-domain failure class and passes through real ingestion, detection, investigation, planning, policy, and governed execution. No outcome is fabricated.</p></div><div className="flex flex-wrap items-center gap-2"><select aria-label="Failure scenario" value={selectedScenario} onChange={(event) => setSelectedScenario(event.target.value)} className="h-9 border border-slate-200 bg-white/80 px-3 font-mono text-[10px] uppercase tracking-wider"><option value="upi-outage">UPI issuer outage</option><option value="provider-outage">Gateway outage</option><option value="insufficient-funds">Insufficient funds</option><option value="already-paid">Already paid</option><option value="high-value">High-value review</option><option value="customer-abandonment">Customer abandonment</option></select><AlertDialog><AlertDialogTrigger render={<Button disabled={inject.isPending} />}><Activity />{inject.isPending ? "Injecting…" : "Inject scenario"}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Inject {selectedScenario.replaceAll("-", " ")}?</AlertDialogTitle><AlertDialogDescription>This runs a deterministic, labelled batch through Sentinel’s real ingestion and governance pipeline. It does not represent production money or synthesize provider recovery.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => inject.mutate(selectedScenario)}>Inject scenario</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div></section>
    <section aria-label="Failure Lab scenarios" className="mb-6"><div className="mb-4"><p className="eyebrow">Failure Lab</p><h2 className="mt-2 text-lg font-semibold">Refusal is a successful outcome when safety requires it</h2></div>{scenarios.isLoading ? <div className="py-16 text-center font-mono text-xs text-slate-400">LOADING SAFETY EVIDENCE</div> : scenarios.error ? <div className="py-16 text-center font-mono text-xs text-[#ef4444]">FAILURE LAB DATA UNAVAILABLE</div> : scenarios.data?.length ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{scenarios.data.map((scenario) => <button key={scenario.id} type="button" disabled={runLab.isPending} onClick={() => runLab.mutate(scenario.id)} className="cursor-pointer rounded-xl border border-slate-200 bg-white/75 p-6 text-left shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-[#2563eb]/40 hover:shadow-md disabled:cursor-wait disabled:opacity-60"><div className="flex items-center justify-between gap-3"><span className={`rounded-full border px-2 py-1 font-mono text-[8px] tracking-widest ${scenario.mode === "REAL_RAZORPAY_TEST_MODE" ? "border-[#22c55e]/30 bg-emerald-50 text-emerald-700" : scenario.mode === "SHADOW_ONLY" ? "border-[#f59e0b]/30 bg-amber-50 text-amber-700" : "border-violet-200 bg-violet-50 text-violet-700"}`}>{scenario.mode.replaceAll("_", " ")}</span><span className="font-mono text-[8px] text-slate-400">{scenario.expectedSafetyOutcome.replaceAll("_", " ")}</span></div><h3 className="mt-5 font-mono text-xs tracking-widest text-slate-900 uppercase">{scenario.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{scenario.description}</p><p className="mt-4 font-mono text-[9px] tracking-widest text-[#2563eb]">{scenario.runnable ? "RUN EVIDENCE CHECK →" : "REQUIRES SIGNED EVENT →"}</p></button>)}</div> : <div className="py-16 text-center font-mono text-xs text-slate-400"><p className="tracking-[0.2em] uppercase">No scenarios available</p></div>}
      {runLab.isPending && <div className="mt-4 flex items-center gap-3 border border-primary/20 bg-primary/[.035] p-5" aria-live="polite"><span className="size-2 rounded-full bg-primary" /><div><p className="font-mono text-xs font-semibold">Checking existing Sentinel evidence</p><p className="mt-1 text-xs text-muted-foreground">Waiting for the backend evaluation or refusal result. No outcome is being simulated.</p></div></div>}
      {runLab.data && <div className={`mt-4 border p-5 ${runLab.data.safetyDemonstrationPassed ? "border-[#22c55e]/30 bg-[#22c55e]/5" : "border-[#f59e0b]/30 bg-[#f59e0b]/5"}`}><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-mono text-xs font-semibold">{runLab.data.scenario.title}</p><span className="test-label">{runLab.data.status.replaceAll("_", " ")}</span></div><ol className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{failureLabTrace(runLab.data).map((step) => <li key={step.label} className="border border-slate-200 bg-white/60 p-3"><div className="flex items-center justify-between gap-2"><p className="font-mono text-[9px] font-semibold tracking-wider">{step.label}</p><StatePill value={step.state} /></div><p className="mt-2 text-xs leading-5 text-slate-600">{step.detail}</p></li>)}</ol><p className="mt-4 text-sm text-[#888888]">{runLab.data.observedBehavior}</p><ul className="mt-3 space-y-1 font-mono text-[10px] text-[#444444]">{runLab.data.evidence.map((line) => <li key={line}>• {line}</li>)}</ul><p className="mt-3 font-mono text-[9px] text-slate-400">EVALUATED {new Date(runLab.data.evaluatedAt).toLocaleString()}</p></div>}
    </section>
    <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><section className="glass-panel rounded-2xl p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl border border-primary/25 bg-primary/10"><FlaskConical className="size-5 text-primary" /></div><div><p className="eyebrow">Five-minute reviewer path</p><h2 className="mt-1 text-lg font-semibold">A provably live Test Mode flow</h2></div></div><ol className="mt-7 space-y-0">{[
      ["01", "Inject", "Replay labelled UPI degradation through batch ingestion and rule-based detection."], ["02", "Investigate", "Run analyst and root-cause agents; Gemini outage still produces a bounded diagnosis."], ["03", "Plan & policy", "See every deterministic PASS/FAIL and why the action is AUTO, HUMAN, or DENY."], ["04", "Execute", "Create exactly one Razorpay Test Mode Payment Link with UPI hidden."], ["05", "Observe", "Refresh after the signed webhook to reconcile recovered revenue exactly once."],
    ].map(([n, title, text], index) => <li key={n} className="grid grid-cols-[34px_1fr] gap-3"><div className="flex flex-col items-center"><span className="grid size-7 place-items-center rounded-full border border-primary/25 bg-primary/8 text-[10px] font-bold text-primary">{n}</span>{index < 4 && <span className="h-full w-px bg-white/10" />}</div><div className="pb-6"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></li>)}</ol>
      <p className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><Activity className="size-3.5" />Launch Gateway Outage above to begin this workflow.<ArrowRight className="size-3.5" /></p>
    </section><aside className="space-y-4"><div className="glass-panel rounded-2xl p-5"><ShieldCheck className="size-5 text-emerald-300" /><h2 className="mt-4 font-semibold">Demo safety</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-muted-foreground"><li>• No production funds or credentials reach the browser.</li><li>• One active recovery is enforced by PostgreSQL.</li><li>• Webhook payloads remain server-side.</li><li>• Duplicate deliveries are visible only as safe audit facts.</li></ul></div><div className="glass-panel rounded-2xl p-5"><DatabaseZap className="size-5 text-destructive" /><h2 className="mt-4 font-semibold">Reset synthetic state</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Resets active synthetic incident and payment-event state so the scenario can be replayed. Append-only audit and evaluation history remains preserved.</p><AlertDialog open={resetOpen} onOpenChange={(open) => { if (!reset.isPending) setResetOpen(open); }}><AlertDialogTrigger render={<Button variant="destructive" className="mt-5 w-full" disabled={reset.isPending} />}><RotateCcw />{reset.isPending ? "Resetting…" : "Reset demo"}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset the synthetic demo?</AlertDialogTitle><AlertDialogDescription>Reset synthetic incident and payment-event state. Append-only audit and evaluation evidence will remain preserved.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={reset.isPending}>Keep state</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={reset.isPending} onClick={(event) => { event.preventDefault(); reset.mutate(); }}>{reset.isPending ? "Resetting…" : "Reset synthetic data"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></aside></div>
  </div>;
}

function StatePill({ value }: { value: string }) {
  const good = value === "COMPLETE" || value === "SAFE_REFUSAL";
  return <span className={`font-mono text-[8px] ${good ? "text-[#15803d]" : "text-[#b45309]"}`}>{value.replaceAll("_", " ")}</span>;
}
