"use client";

import { useRouter } from "next/navigation";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, DatabaseZap, FlaskConical, RotateCcw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api, shortId } from "@/lib/api";
import { useStatusIsland } from "@/components/providers";
import { PageHeader } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

export default function DemoPage() {
  const client = useQueryClient(); const router = useRouter(); const { emit } = useStatusIsland();
  const refreshAll = () => Promise.all([client.invalidateQueries({ queryKey: ["incidents"] }), client.invalidateQueries({ queryKey: ["metrics"] }), client.invalidateQueries({ queryKey: ["approvals"] })]);
  const reset = useMutation({ mutationFn: api.reset, onSuccess: async () => { await refreshAll(); emit({ title: "Demo reset complete", detail: "Synthetic events and incidents cleared" }); toast.success("Synthetic state reset"); }, onError: (error: Error) => toast.error(error.message) });
  const inject = useMutation({ mutationFn: api.inject, onSuccess: async (result) => { await refreshAll(); const id = result.incidentIds?.[0]; emit({ title: "Incident detected", detail: id ? `UPI outage · ${shortId(id)}` : "UPI outage replayed" }); toast.success("UPI outage passed through ingestion and detection"); if (id) router.push(`/incidents/${id}`); }, onError: (error: Error) => toast.error(error.message) });
  return <div><PageHeader eyebrow="Controlled demonstration" title="Run the Sentinel story" description="Reset synthetic state, inject a labelled UPI outage through the real ingestion and detection pipeline, then operate the incident without Postman." />
    <div className="mb-4"><span className="test-label">Test mode / Synthetic evaluation</span></div>
    <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><section className="glass-panel rounded-2xl p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl border border-primary/25 bg-primary/10"><FlaskConical className="size-5 text-primary" /></div><div><p className="eyebrow">Five-minute reviewer path</p><h2 className="mt-1 text-lg font-semibold">A provably live Test Mode flow</h2></div></div><ol className="mt-7 space-y-0">{[
      ["01", "Inject", "Replay labelled UPI degradation through batch ingestion and rule-based detection."], ["02", "Investigate", "Run analyst and root-cause agents; Gemini outage still produces a bounded diagnosis."], ["03", "Plan & policy", "See every deterministic PASS/FAIL and why the action is AUTO, HUMAN, or DENY."], ["04", "Execute", "Create exactly one Razorpay Test Mode Payment Link with UPI hidden."], ["05", "Observe", "Refresh after the signed webhook to reconcile recovered revenue exactly once."],
    ].map(([n, title, text], index) => <li key={n} className="grid grid-cols-[34px_1fr] gap-3"><div className="flex flex-col items-center"><span className="grid size-7 place-items-center rounded-full border border-primary/25 bg-primary/8 text-[10px] font-bold text-primary">{n}</span>{index < 4 && <span className="h-full w-px bg-white/10" />}</div><div className="pb-6"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></li>)}</ol>
      <AlertDialog><AlertDialogTrigger render={<Button size="lg" disabled={inject.isPending} />}><Activity />{inject.isPending ? "Injecting…" : "Inject UPI outage"}<ArrowRight /></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Inject the synthetic UPI outage?</AlertDialogTitle><AlertDialogDescription>This posts the fixed labelled batch through Sentinel’s real ingestion and detection pipeline. It is Test Mode data only.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => inject.mutate()}>Inject scenario</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    </section><aside className="space-y-4"><div className="glass-panel rounded-2xl p-5"><ShieldCheck className="size-5 text-emerald-300" /><h2 className="mt-4 font-semibold">Demo safety</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-muted-foreground"><li>• No production funds or credentials reach the browser.</li><li>• One active recovery is enforced by PostgreSQL.</li><li>• Webhook payloads remain server-side.</li><li>• Duplicate deliveries are visible only as safe audit facts.</li></ul></div><div className="glass-panel rounded-2xl p-5"><DatabaseZap className="size-5 text-destructive" /><h2 className="mt-4 font-semibold">Reset synthetic state</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Clears the demo’s synthetic event and incident state so the scenario can be replayed from a known baseline.</p><AlertDialog><AlertDialogTrigger render={<Button variant="destructive" className="mt-5 w-full" disabled={reset.isPending} />}><RotateCcw />{reset.isPending ? "Resetting…" : "Reset demo"}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset the synthetic demo?</AlertDialogTitle><AlertDialogDescription>This removes synthetic incident and payment-event state. Append-only production-style audit safeguards remain part of the application design.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep state</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => reset.mutate()}>Reset synthetic data</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></aside></div>
  </div>;
}
